### ISSUE TITLE
v0.1.0 - milestone

### ISSUE THREAD

**Issue by dd84ai** [darklab8/darklab_autogit#1]
- [x] Parse tags to semantic versioning (simple version)
- [x] Parse commit into conventional commit
- [x] hook commit-msg validate for being good to conventional commits
- [x] Parse changelog into git conventional commits
- [x] Calculate next semantic version as latest succesfully parsed tag + calculations from changelog
- [x] Render changelog into user view way
