### ISSUE TITLE
v0.2.0 - milestone

### ISSUE THREAD

**Issue by dd84ai** [darklab8/darklab_autogit#2]
- [x] Add Issue parsing and rendering
- [x] Test to have it working xD previous tag i think is not detected
- [x] Add --no-v option to disable v
- [x] Add ability to set builddata
- [x] Add command to enable or disable git hooks into autogit
- [x] Add printing by scope
