### ISSUE TITLE
v0.3.0 - milestone

### ISSUE THREAD

**Issue by dd84ai** [darklab8/darklab_autogit#3]
- [x] Refactor package order to be self explanatory
- [x] Refactor activate-deactivate to `hook` section
- [x] Refactor: Generate hook folder on your own?
- [x] Feat: Add flag, --no-newline to `version` command, for CI purposes
- [x] Refactor all regexes to autogit.yml as option
- [x] Feat: Add ability for strict rule => Max length of header N
- [x] Feat: Add ability for strict rule => Issue must be defined in commit
- [x] Feat: Add ability for strict rule => Scope must be defined
- [x] Feat: Add more configs for validation of commits
- [x] Feat: Add CI check for all changelog/commits being valid
- [x] Feat: Compiled for macos and other archs (removed CGO dep)
- [x] Feat: Add ability to set Alpha/Beta/Prerelease?
