### ISSUE TITLE
0.4.0 milestone

### ISSUE THREAD

**Issue by dd84ai** [darklab8/darklab_autogit#4]
- [x] move types to settings
- [x] refactor cmd params
- [x] write pipeline with it
- [x] refactor shell scripts
  - [x] tag
  - [x] push
  - [x] hook
- [x] refactor second build?
- [x] perhaps to make idempotents tag/push
- [x] moving tag push into param
- [x] write workflow with automated fully deployment
